"""empty message

Revision ID: 87697e664633
Revises: 76a3539e1b7d
Create Date: 2025-08-29 20:05:59.805063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87697e664633'
down_revision = '76a3539e1b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posted', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('posted')

    # ### end Alembic commands ###
